service: tcc-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: sa-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
    TWILIO_SERVICE_SID: ${env:TWILIO_SERVICE_SID}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
        - cognito-idp:*
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'

functions:
  createUser:
    handler: dist/modules/user/create/handler.createUser
    events:
      - http:
          path: users
          method: post
          cors: true
  sendCode:
    handler: dist/modules/code/send/handler.sendCode
    events:
      - http:
          path: code/sendCode
          method: post
          cors: true
  verifyCode:
    handler: dist/modules/code/verify/handler.verifyCode
    events:
      - http:
          path: code/verifyCode
          method: post
          cors: true
  getUserCognito:
    handler: dist/modules/code/getUserCognito/handler.getUserCognito
    events:
      - http:
          path: cognito/user
          method: post
          cors: true

plugins:
  - serverless-offline