service: tcc-api

provider:
 name: aws
 runtime: nodejs14.x
 stage: dev
 region: sa-east-1
 environment:
  MONGODB_URI: ${env:MONGODB_URI}
  JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
  TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
  TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
  TWILIO_SERVICE_SID: ${env:TWILIO_SERVICE_SID}
 iamRoleStatements:
  - Effect: Allow
    Action:
     - logs:CreateLogGroup
     - logs:CreateLogStream
     - logs:PutLogEvents
    Resource: "*"

functions:
 sendCode:
  handler: dist/src/handlers.sendCode
  events:
   - http:
      path: code/send
      method: post
      cors: true

plugins:
 - serverless-offline
