service: tcc-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: sa-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
        - cognito-idp:*
      Resource: '*'

functions:
  createUser:
    handler: dist/modules/user/create/handler.createUser
    events:
      - http:
          path: users
          method: post
          cors: true
  sendCode:
    handler: dist/modules/code/send/handler.sendCode
    events:
      - http:
          path: code/sendCode
          method: post
          cors: true
  verifyCode:
    handler: dist/modules/code/verify/handler.verifyCode
    events:
      - http:
          path: code/verifyCode
          method: post
          cors: true

plugins:
  - serverless-offline